import type { NextPage } from 'next'
import Head from 'next/head'
import { Heading, Text, Flex } from '@radix-ui/themes'
import Image from 'next/image'
import { useTranslations } from 'next-intl'
import Link from 'next/link'


const Offline: NextPage = () => {
    const t  = useTranslations()

    return (
        <>
            <Head>
                <title>Offline</title>
                <meta name="description" content="Generated by create next app" />
                <Link rel="icon" href="favicon.ico" />
            </Head>
            <Flex direction={'column'} py={'5'}>
                <Image src={'/assets/images/offline.png'} fill sizes='(width: 768px) 100%' alt={'offline'} />
                <Heading size={'3'}>{t('offlineHead')}</Heading>
                <Text>{t("offlineParagraph")}</Text>    
            </Flex>
        </>
    )
}

export default Offline
